In [1]:
import numpy as np

# Input tokens (example embeddings)
X = np.array([
    [1, 0, 1, 0],
    [0, 2, 0, 2],
    [1, 1, 1, 1]
])

# Initialize weights
W_Q = np.random.rand(4, 4)
W_K = np.random.rand(4, 4)
W_V = np.random.rand(4, 4)

# Compute Q, K, V
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

# Compute attention scores
scores = Q @ K.T

# Scale scores
dk = K.shape[1]
scaled_scores = scores / np.sqrt(dk)

# Softmax function
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

# Attention weights
attention_weights = softmax(scaled_scores)

# Final output
output = attention_weights @ V

print("Attention Weights:\n", attention_weights)
print("Output:\n", output)

Attention Weights:
 [[0.03328034 0.49592324 0.47079641]
 [0.00976907 0.6385773  0.35165363]
 [0.00484609 0.58384559 0.41130833]]
Output:
 [[0.99897998 2.68620577 2.89988784 3.00506311]
 [1.01579649 2.75747543 2.99436178 3.07344685]
 [1.01654419 2.75011724 2.98011216 3.06929551]]
